# Generated by Django 3.2.20 on 2023-08-09 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('BenchmarkID', models.AutoField(primary_key=True, serialize=False)),
                ('BenchmarkName', models.CharField(max_length=255)),
                ('NumberOfIterations', models.IntegerField()),
                ('BenchmarkFlags', models.CharField(max_length=255)),
                ('MTMD', models.IntegerField()),
                ('SizeType', models.IntegerField()),
                ('SizeNumber', models.CharField(max_length=255)),
                ('Dimension', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HardwareConfiguration',
            fields=[
                ('HardwareInfo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('DeviceID', models.IntegerField()),
                ('DeviceTypeGPU', models.CharField(max_length=255)),
                ('DeviceName', models.CharField(max_length=255)),
                ('GlobalMemorySize', models.IntegerField()),
                ('LocalMemorySize', models.IntegerField()),
                ('GlobalThreadNumber', models.IntegerField()),
                ('LocalThreadNumber', models.IntegerField()),
                ('MaxFrequency', models.FloatField()),
                ('ComputeUnits', models.IntegerField()),
                ('DeviceExtensions', models.CharField(max_length=255)),
                ('ComputeCapability', models.CharField(max_length=255)),
                ('DevicePartitioning', models.CharField(max_length=255)),
                ('MaxWorkItemDimension', models.IntegerField()),
                ('UnifiedMemory', models.BooleanField()),
                ('AtomicSupport', models.BooleanField()),
                ('HalfPrecisionSupport', models.BooleanField()),
                ('DoubleSupport', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('RunID', models.AutoField(primary_key=True, serialize=False)),
                ('DateTime', models.DateTimeField()),
                ('CommitPoint', models.CharField(max_length=255)),
                ('LatestRelease', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareConfiguration',
            fields=[
                ('SoftwareID', models.AutoField(primary_key=True, serialize=False)),
                ('OSVersion', models.CharField(max_length=255)),
                ('DriverVersion', models.CharField(max_length=255)),
                ('JVMVersion', models.CharField(max_length=255)),
                ('GCCVersion', models.CharField(max_length=255)),
                ('MavenVersion', models.CharField(max_length=255)),
                ('CmakeVersion', models.CharField(max_length=255)),
                ('PythonVersion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaskGraphResults',
            fields=[
                ('TaskGraphID', models.AutoField(primary_key=True, serialize=False)),
                ('MinimumKernelsTime', models.IntegerField()),
                ('KernelAverage', models.IntegerField()),
                ('Copy_IN', models.IntegerField()),
                ('Copy_OUT', models.IntegerField()),
                ('Compilation_Graal', models.IntegerField()),
                ('Compilation_Driver', models.IntegerField()),
                ('Dispatch_Time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalResults',
            fields=[
                ('ResultID', models.AutoField(primary_key=True, serialize=False)),
                ('TotalAverageTime', models.BigIntegerField()),
                ('TotalMedianTime', models.BigIntegerField()),
                ('TotalFirstIteration', models.BigIntegerField()),
                ('TotalBest', models.BigIntegerField()),
                ('TotalMinimum', models.BigIntegerField()),
                ('TotalSpeedup', models.FloatField()),
                ('BenchmarkID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_results', to='DashboardApp.benchmark')),
            ],
        ),
        migrations.CreateModel(
            name='TaskResults',
            fields=[
                ('TaskID', models.AutoField(primary_key=True, serialize=False)),
                ('KernelTime', models.IntegerField()),
                ('CodeGenerationTime', models.IntegerField()),
                ('DriverCompilationTime', models.IntegerField()),
                ('HardwareInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_results', to='DashboardApp.hardwareconfiguration')),
                ('SoftwareInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_results', to='DashboardApp.softwareconfiguration')),
                ('TaskGraphID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_results', to='DashboardApp.taskgraphresults')),
            ],
        ),
        migrations.AddField(
            model_name='taskgraphresults',
            name='ResultID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_graph_results', to='DashboardApp.totalresults'),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='RunID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='DashboardApp.run'),
        ),
    ]
